C:\Users\USER\Documents\Dev Projects\mypandablog\blog\admin.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\admin.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\admin.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\admin.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /exploring-the-symbolism-of-flowers-in-anime/ HTTP/1.1" 200 38045
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 17342
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2806
"GET /static/admin/css/base.css HTTP/1.1" 200 22700
"GET /static/admin/js/theme.js HTTP/1.1" 200 1999
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2960
"GET /static/admin/css/login.css HTTP/1.1" 200 1019
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18875
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3142
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 33820
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 470
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 334
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 383
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 395
"GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 33820
"GET /contact/ HTTP/1.1" 200 30657
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 49, in frontpage
    return render(request, 'frontpage.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 326, in render
    if match:
       ^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 414, in __bool__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ~~~~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases or bool(combinator),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ~~~~~~~~~~~~~~~^
        with_col_aliases=with_col_aliases,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1213, in get_related_selections
    raise FieldError(
    ...<6 lines>...
    )
django.core.exceptions.FieldError: Non-relational field given in select_related: 'author'. Choices are: category
"GET / HTTP/1.1" 500 224923
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0018_convert_author_to_foreignkey.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0018_convert_author_to_foreignkey.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0018_convert_author_to_foreignkey.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0018_convert_author_to_foreignkey.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0018_convert_author_to_foreignkey.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: blog_post.author_user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 49, in frontpage
    return render(request, 'frontpage.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 326, in render
    if match:
       ^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 414, in __bool__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: blog_post.author_user_id
"GET / HTTP/1.1" 500 271171
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: blog_post.author_user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 49, in frontpage
    return render(request, 'frontpage.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 326, in render
    if match:
       ^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 414, in __bool__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: blog_post.author_user_id
"GET / HTTP/1.1" 500 271169
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: blog_post.author_user_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 49, in frontpage
    return render(request, 'frontpage.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 326, in render
    if match:
       ^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 414, in __bool__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: blog_post.author_user_id
"GET / HTTP/1.1" 500 271172
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0021_auto_20241115_1601.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0021_auto_20241115_1601.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0021_auto_20241115_1601.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0021_auto_20241115_1601.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0021_auto_20241115_1601.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\management\commands\fix_author_field.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\management\commands\fix_author_field.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\management\commands\fix_author_field.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\management\commands\fix_author_field.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\management\commands\fix_author_field.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\management\commands\fix_author_field.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\management\commands\fix_author_field.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 30773
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /about/ HTTP/1.1" 200 24496
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
Internal Server Error: /category/anime/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 133, in category_detail
    return render(request, 'category_detail.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_detail' with arguments '('exploring-the-symbolism-of-flowers-in-anime',)' not found. 1 pattern(s) tried: ['(?P<category_slug>[-a-zA-Z0-9_]+)/(?P<post_slug>[-a-zA-Z0-9_]+)/\\Z']
"GET /category/anime/ HTTP/1.1" 500 194876
"GET / HTTP/1.1" 200 30739
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET / HTTP/1.1" 200 30739
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /category/anime/ HTTP/1.1" 200 23938
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /anime/top-10-must-watch-anime-for-beginners/ HTTP/1.1" 200 39227
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
"GET /accounts/logout/ HTTP/1.1" 200 15123
"POST /accounts/logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 30738
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /profile/ HTTP/1.1" 302 0
"GET /accounts/login/?next=/profile/ HTTP/1.1" 200 15754
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 93, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 53, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 82, in post
    response = self.form_valid(form)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 106, in form_valid
    return form.login(self.request, redirect_url=redirect_url)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\forms.py", line 199, in login
    ret = flows.login.perform_password_login(request, credentials, login)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\internal\flows\login.py", line 74, in perform_password_login
    return perform_login(request, login)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\internal\flows\login.py", line 83, in perform_login
    return resume_login(request, login)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\internal\flows\login.py", line 92, in resume_login
    response = ctrl.handle()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\stages.py", line 109, in handle
    response, cont = stage.handle()
                     ~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\stages.py", line 148, in handle
    send_email_confirmation(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        self.request, login.user, signup=login.signup, email=login.email
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\utils.py", line 284, in send_email_confirmation
    return flows.email_verification.send_verification_email(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        request, user, signup=signup, email=email
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\internal\flows\email_verification.py", line 214, in send_verification_email
    email_address = EmailAddress.objects.add_email(
        request, user, email, signup=signup, confirm=True
    )
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\managers.py", line 60, in add_email
    email_address.send_confirmation(request, signup=signup)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\models.py", line 107, in send_confirmation
    confirmation.send(request, signup=signup)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\models.py", line 135, in send
    get_adapter().send_confirmation_mail(request, self, signup)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\adapter.py", line 637, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\adapter.py", line 201, in send_mail
    msg.send()
    ~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\mail\backends\smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 864, in create_connection
    raise exceptions[0]
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
"POST /accounts/login/ HTTP/1.1" 500 263999
"GET /accounts/login/?next=/profile/ HTTP/1.1" 200 15542
"GET /accounts/signup/ HTTP/1.1" 200 15898
"POST /accounts/signup/ HTTP/1.1" 200 16036
"GET /accounts/login/ HTTP/1.1" 200 15457
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 93, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 53, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 82, in post
    response = self.form_valid(form)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 106, in form_valid
    return form.login(self.request, redirect_url=redirect_url)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\forms.py", line 199, in login
    ret = flows.login.perform_password_login(request, credentials, login)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\internal\flows\login.py", line 74, in perform_password_login
    return perform_login(request, login)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\internal\flows\login.py", line 83, in perform_login
    return resume_login(request, login)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\internal\flows\login.py", line 92, in resume_login
    response = ctrl.handle()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\stages.py", line 109, in handle
    response, cont = stage.handle()
                     ~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\stages.py", line 148, in handle
    send_email_confirmation(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        self.request, login.user, signup=login.signup, email=login.email
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\utils.py", line 284, in send_email_confirmation
    return flows.email_verification.send_verification_email(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        request, user, signup=signup, email=email
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\internal\flows\email_verification.py", line 208, in send_verification_email
    email_address.send_confirmation(request, signup=signup)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\models.py", line 107, in send_confirmation
    confirmation.send(request, signup=signup)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\models.py", line 135, in send
    get_adapter().send_confirmation_mail(request, self, signup)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\adapter.py", line 637, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\adapter.py", line 201, in send_mail
    msg.send()
    ~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\mail\message.py", line 301, in send
    return self.get_connection(fail_silently).send_messages([self])
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\mail\backends\smtp.py", line 128, in send_messages
    new_conn_created = self.open()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\mail\backends\smtp.py", line 86, in open
    self.connection = self.connection_class(
                      ~~~~~~~~~~~~~~~~~~~~~^
        self.host, self.port, **connection_params
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
                                    self.source_address)
                                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 864, in create_connection
    raise exceptions[0]
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 849, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
"POST /accounts/login/ HTTP/1.1" 500 258850
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /profile/ HTTP/1.1" 302 0
"GET /accounts/login/?next=/profile/ HTTP/1.1" 200 15542
"GET /profile/ HTTP/1.1" 302 0
"GET /accounts/login/?next=/profile/ HTTP/1.1" 200 15542
"GET / HTTP/1.1" 200 30739
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /accounts/logout/ HTTP/1.1" 200 15087
"POST /accounts/logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 30738
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /about/ HTTP/1.1" 200 24469
"GET /contact/ HTTP/1.1" 200 25376
"GET /privacy-policy/ HTTP/1.1" 200 29694
"GET /terms-and-conditions/ HTTP/1.1" 200 22820
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 150, in search
    return render(request, 'search.html', {
        'query': query,
        'posts': posts,
        'categories': categories
    })
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_detail' with arguments '('exploring-the-symbolism-of-flowers-in-anime',)' not found. 1 pattern(s) tried: ['(?P<category_slug>[-a-zA-Z0-9_]+)/(?P<post_slug>[-a-zA-Z0-9_]+)/\\Z']
"GET /search/?query=anime HTTP/1.1" 500 194930
"GET /category/anime/ HTTP/1.1" 200 23900
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /anime/exploring-the-symbolism-of-flowers-in-anime/ HTTP/1.1" 200 31852
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"POST /anime/exploring-the-symbolism-of-flowers-in-anime/ HTTP/1.1" 302 0
"GET /accounts/login/ HTTP/1.1" 200 15672
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0001_initial.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0001_initial.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0001_initial.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\migrations\0001_initial.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 93, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 53, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 72, in get
    response = super().get(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 116, in get_context_data
    ret = super().get_context_data(**kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 135, in get_context_data
    ret = super().get_context_data(**kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 92, in get_form
    form = super().get_form(form_class)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py", line 52, in __init__
    self.fields['remember'].widget.attrs['class'] = 'h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded'
    ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'remember'
"GET /accounts/login/ HTTP/1.1" 500 189572
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 23058
"GET /accounts/signup/ HTTP/1.1" 200 16356
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 93, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 53, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 72, in get
    response = super().get(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 116, in get_context_data
    ret = super().get_context_data(**kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 135, in get_context_data
    ret = super().get_context_data(**kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 92, in get_form
    form = super().get_form(form_class)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py", line 52, in __init__
    self.fields['remember'].widget.attrs['class'] = 'h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded'
    ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'remember'
"GET /accounts/login/ HTTP/1.1" 500 189384
"GET / HTTP/1.1" 200 23058
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 93, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 53, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 72, in get
    response = super().get(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 116, in get_context_data
    ret = super().get_context_data(**kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 135, in get_context_data
    ret = super().get_context_data(**kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 92, in get_form
    form = super().get_form(form_class)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py", line 52, in __init__
    self.fields['remember'].widget.attrs['class'] = 'h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded'
    ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'remember'
"GET /accounts/login/ HTTP/1.1" 500 189384
"GET /accounts/signup/ HTTP/1.1" 200 16354
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 23059
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\decorators.py", line 12, in wrap
    resp = function(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 93, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 53, in dispatch
    response = super().dispatch(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 72, in get
    response = super().get(request, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\views.py", line 116, in get_context_data
    ret = super().get_context_data(**kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 135, in get_context_data
    ret = super().get_context_data(**kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\allauth\account\mixins.py", line 92, in get_form
    form = super().get_form(form_class)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\views\generic\edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py", line 81, in __init__
    self.fields['remember'].widget.attrs.update({
    ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'remember'
"GET /accounts/login/ HTTP/1.1" 500 189670
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\markdown2.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\markdown2.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\markdown2.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\markdown2.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\markdown2.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\markdown2.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /accounts/login/ HTTP/1.1" 200 15536
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
"POST /accounts/login/ HTTP/1.1" 200 15678
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 17346
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 30141
"GET /admin/auth/user/ HTTP/1.1" 200 32531
"GET /static/admin/css/changelists.css HTTP/1.1" 200 7149
"GET /static/admin/js/actions.js HTTP/1.1" 200 8271
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9282
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 355
"GET /static/admin/js/core.js HTTP/1.1" 200 6392
"GET /static/admin/js/urlify.js HTTP/1.1" 200 8056
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1574
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 296030
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 439
"GET /static/admin/img/search.svg HTTP/1.1" 200 461
"GET /static/admin/js/filters.js HTTP/1.1" 200 1008
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 331297
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 334
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 584
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1116
"GET /accounts/login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 23029
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'Admin'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 159, in profile
    user_posts = Post.objects.filter(author=request.user.username).order_by('-created_at')
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
        "Field '%s' expected a number but got %r." % (self.name, value),
    ) from e
ValueError: Field 'id' expected a number but got 'Admin'.
"GET /profile/ HTTP/1.1" 500 154794
"GET /accounts/logout/ HTTP/1.1" 200 15123
"POST /accounts/logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 22998
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 23235
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: core.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: core.html
"GET /accounts/signup/ HTTP/1.1" 500 159461
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        template_name,
        ^^^^^^^^^^^^^^
        skip=history,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: core.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 109, in render
    reraise(exc, self.backend)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: core.html
"GET /accounts/login/ HTTP/1.1" 500 158671
"GET / HTTP/1.1" 200 23204
"GET /accounts/login/ HTTP/1.1" 200 23164
"GET /accounts/signup/ HTTP/1.1" 200 24550
"POST /accounts/signup/ HTTP/1.1" 302 0
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 166, in profile
    return render(request, 'blog/profile.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/profile.html
"GET /profile/ HTTP/1.1" 500 115836
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /accounts/signup/ HTTP/1.1" 302 0
"GET /accounts/login/ HTTP/1.1" 302 0
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
"GET /accounts/signup/ HTTP/1.1" 302 0
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 166, in profile
    return render(request, 'account/profile.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_create' not found. 'post_create' is not a valid view function or pattern name.
"GET /profile/ HTTP/1.1" 500 186286
"GET /accounts/login/ HTTP/1.1" 302 0
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 166, in profile
    return render(request, 'account/profile.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_create' not found. 'post_create' is not a valid view function or pattern name.
"GET /profile/ HTTP/1.1" 500 185955
"GET /accounts/login/ HTTP/1.1" 302 0
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 166, in profile
    return render(request, 'account/profile.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post_create' not found. 'post_create' is not a valid view function or pattern name.
"GET /profile/ HTTP/1.1" 500 185955
"GET / HTTP/1.1" 200 23053
"GET /profile/ HTTP/1.1" 200 23941
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 23021
"GET /profile/ HTTP/1.1" 200 23904
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /contact/ HTTP/1.1" 200 26075
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET /contact/ HTTP/1.1" 200 26044
"GET /contact/ HTTP/1.1" 200 26044
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET /accounts/logout/ HTTP/1.1" 302 0
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 17554
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 17522
"GET /profile/ HTTP/1.1" 302 0
"GET /accounts/login/?next=/profile/ HTTP/1.1" 200 17761
"POST /accounts/login/ HTTP/1.1" 302 0
"GET /profile/ HTTP/1.1" 200 19935
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /accounts/login/ HTTP/1.1" 302 0
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET /profile/ HTTP/1.1" 200 19899
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /profile/ HTTP/1.1" 302 0
"GET /accounts/login/?next=/profile/ HTTP/1.1" 200 25031
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 23340
"GET /accounts/login/ HTTP/1.1" 200 23442
"POST /accounts/login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 23308
"GET /accounts/signup/ HTTP/1.1" 302 0
"GET /accounts/signup/ HTTP/1.1" 302 0
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 24809
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 24777
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET /profile/ HTTP/1.1" 302 0
"GET /accounts/login/?next=/profile/ HTTP/1.1" 200 25738
"GET /accounts/login/ HTTP/1.1" 200 24157
"POST /accounts/login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 24776
"GET /profile/ HTTP/1.1" 200 26604
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /contact/ HTTP/1.1" 200 31085
"GET / HTTP/1.1" 200 24776
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET /profile/ HTTP/1.1" 200 26567
"GET /static/images/default-avatar.png HTTP/1.1" 404 2002
"GET /contact/ HTTP/1.1" 200 31056
"GET / HTTP/1.1" 200 24776
"GET /contact/ HTTP/1.1" 200 31055
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET /accounts/logout/ HTTP/1.1" 302 0
