Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
- Broken pipe from ('127.0.0.1', 51943)
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 49, in frontpage
    return render(request, 'frontpage.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'account_login' not found. 'account_login' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 187755
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 12621
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 13578
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4527
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 49, in frontpage
    return render(request, 'frontpage.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'account_login' not found. 'account_login' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 187890
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 49, in frontpage
    return render(request, 'frontpage.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'account_login' not found. 'account_login' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 187890
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "c:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 49, in frontpage
    return render(request, 'frontpage.html', context)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'account_login' not found. 'account_login' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 187890
"GET / HTTP/1.1" 200 18401
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 12310
"GET /static/vendor/adminlte/css/adminlte.min.css HTTP/1.1" 200 1382975
"GET /static/vendor/fontawesome-free/css/all.min.css HTTP/1.1" 200 59344
"GET /static/vendor/bootswatch/cyborg/bootstrap.min.css HTTP/1.1" 200 164597
"GET /static/images/logo.png HTTP/1.1" 404 1859
"GET /static/vendor/bootstrap/js/bootstrap.min.js HTTP/1.1" 200 62440
"GET /static/jazzmin/css/main.css HTTP/1.1" 200 16969
"GET /static/vendor/fontawesome-free/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 78196
"GET /static/vendor/adminlte/js/adminlte.min.js HTTP/1.1" 200 44244
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 18401
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 12621
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 13578
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4527
Not Found: /accounts/logout/
"GET /accounts/logout/ HTTP/1.1" 404 12830
Internal Server Error: /contact/
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 55, in contact
    return render(request, 'blog/contact.html')
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/contact.html
"GET /contact/ HTTP/1.1" 500 107137
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 52, in about
    return render(request, 'blog/about.html')
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/about.html
"GET /about/ HTTP/1.1" 500 107004
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 18401
Internal Server Error: /contact/
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 55, in contact
    return render(request, 'blog/contact.html')
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/contact.html
"GET /contact/ HTTP/1.1" 500 107136
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 52, in about
    return render(request, 'blog/about.html')
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/about.html
"GET /about/ HTTP/1.1" 500 107004
"GET / HTTP/1.1" 200 18369
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 52, in about
    return render(request, 'blog/about.html')
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/about.html
"GET /about/ HTTP/1.1" 500 107005
Internal Server Error: /contact/
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 55, in contact
    return render(request, 'blog/contact.html')
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/contact.html
"GET /contact/ HTTP/1.1" 500 107136
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 12621
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 13578
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4527
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 52, in about
    return render(request, 'blog/about.html')
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/about.html
"GET /about/ HTTP/1.1" 500 107296
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 52, in about
    return render(request, 'blog/about.html')
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/about.html
"GET /about/ HTTP/1.1" 500 107296
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 52, in about
    return render(request, 'blog/about.html')
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/about.html
"GET /about/ HTTP/1.1" 500 107151
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py", line 50, in about
    return render(request, 'blog/about.html')
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/about.html
"GET /about/ HTTP/1.1" 500 105802
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 17881
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /about/ HTTP/1.1" 200 20751
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\USER\Documents\Dev Projects\mypandablog\blog\admin.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\urls\base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\debug_toolbar\middleware.py", line 74, in __call__
    rendered = toolbar.render_toolbar()
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\debug_toolbar\toolbar.py", line 82, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\test\utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\USER\Documents\Dev Projects\mypandablog\venv\Lib\site-packages\django\urls\base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
"GET / HTTP/1.1" 500 142287
C:\Users\USER\Documents\Dev Projects\mypandablog\mypandablog\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 8865
"GET /about/ HTTP/1.1" 200 11735
"GET /contact/ HTTP/1.1" 200 16633
"GET / HTTP/1.1" 200 8865
